# Generated by Django 4.2.3 on 2023-08-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_alter_advertisement_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
